In [12]:
import numpy as np

In [13]:
np.__version__

'2.3.1'

Create and Read

1D Array

In [14]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [15]:
type(arr1)

numpy.ndarray

In [16]:
arr1.shape

(6,)

In [17]:
arr1.dtype

dtype('int64')

In [18]:
arr1.ndim

1

In [19]:
arr1.size

6

2D Array

In [21]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [22]:
arr2.ndim

2

In [ ]:
arr2.shape # (row, col)

(2, 3)

In [24]:
arr2.dtype

dtype('int64')

In [25]:
arr1.size

6

3D Array

In [32]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [33]:
arr3.ndim

3

In [34]:
arr3.shape # (layers, rowsm col)

(3, 2, 3)

In [35]:
arr3.size

18

Create random array

In [37]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.84414756, 0.56809818, 0.92870333],
        [0.19959894, 0.35611726, 0.80038343]],

       [[0.88492716, 0.68539223, 0.0842324 ],
        [0.58408511, 0.69689029, 0.22708035]],

       [[0.65381178, 0.93305421, 0.72289772],
        [0.73924299, 0.0230481 , 0.38174569]]])

In [38]:
randomArr.dtype

dtype('float64')

In [40]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
zeroes.ndim

3

In [43]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [44]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [56]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [57]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [58]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [61]:
arr3[1][0][1]

np.int64(5)

Update & Delete

In [63]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [67]:
a1

array([[[0.93698277, 0.43173959],
        [0.65321809, 0.49420491],
        [0.37187257, 0.76515563]],

       [[0.21403138, 0.44670801],
        [0.90466305, 0.92887255],
        [0.19850446, 0.55534046]]])

In [68]:
a2

array([[[0.79626438, 0.26552365],
        [0.54414861, 0.94795619],
        [0.75147892, 0.05592656]],

       [[0.1240672 , 0.23630256],
        [0.07223768, 0.91374655],
        [0.39320067, 0.5456503 ]]])

Basic Math Operations

In [69]:
np.add(a1, a2)

array([[[1.73324715, 0.69726324],
        [1.1973667 , 1.44216109],
        [1.12335149, 0.82108219]],

       [[0.33809858, 0.68301057],
        [0.97690073, 1.8426191 ],
        [0.59170513, 1.10099076]]])

In [70]:
np.subtract(a1, a2)

array([[[ 0.14071839,  0.16621595],
        [ 0.10906948, -0.45375128],
        [-0.37960634,  0.70922908]],

       [[ 0.08996418,  0.21040545],
        [ 0.83242536,  0.015126  ],
        [-0.1946962 ,  0.00969016]]])

In [71]:
np.divide(a1, a2)

array([[[ 1.17672321,  1.62599301],
        [ 1.20044061,  0.52133729],
        [ 0.4948543 , 13.68143642]],

       [[ 1.72512463,  1.89040698],
        [12.52342282,  1.01655382],
        [ 0.50484264,  1.01775892]]])